spring:
  application:
    name: hdk-hotel
  datasource:
#    username: root
#    password: admin
#    url: jdbc:mysql://localhost:3306/hdk_hotel_db
    username: avnadmin
    password: AVNS_fo1vHdplT3fR_Dv6T4E
    url: jdbc:mysql://avnadmin:AVNS_fo1vHdplT3fR_Dv6T4E@hdk-hotel-db-nkduyc9htk2021-051d.f.aivencloud.com:28431/hdk_hotel_db?ssl-mode=REQUIRED
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      file-size-threshold: 2KB

server:
  port: 9192
