POST http://localhost:9192/rooms/add/new-room
Content-Type: application/json

{
  "photo": "https://www.hotelmonterey.co.jp/upload_file/monhtyo/stay/sng_600_001.jpg",
  "roomType": "Single bed room",
  "roomPrice": "200"
}

###
